### ISSUE TITLE
Machine Learning | Deep Learning

### ISSUE THREAD

**Issue by tomiock** [tomiock/qGAN#3]
- [ ] Types of ML 
- [ ] Types of Neural Nets
- [ ] Genertives Networks

**Comment by namaannn** [comment]
@tomiock kindly assign me this issue, I will write all types of networks

**Comment by sridhatta** [comment]
Hi @tomiock  I am interested to take up this exercise. Please let me know if you can assign it.

**Comment by tomiock** [comment]
oh hi 
sorry but I am not interested in collaborating with anyone on this repository 
and I have already code the neural network
